blank_issues_enabled: true
contact_links:
  - name: Původní 3D model (Lukáš Eršil)
    url: https://github.com/lukasersil/narodni-divadlo-3d
    about: Chyba v samotném modelu divadla (rozměry, chybějící prvek) patří tam.
